export default {
  REVIEWS_FETCH:'REVIEWS_FETCH',
  REVIEWS_FETCH_SORTED:'REVIEWS_FETCH_SORTED',
  REVIEWS_FETCH_SEARCH:'REVIEWS_FETCH_SEARCH',
  REVIEWS_SET_LANGUAGE:'REVIEWS_SET_LANGUAGE',
  REVIEWS_UPDATE:'REVIEWS_UPDATE',
  REVIEWS_UPDATE_ERROR:'REVIEWS_UPDATE_ERROR',
  REVIEWS_SORT_REQUEST: 'REVIEWS_SORT_REQUEST',
  REVIEWS_SORT_SET:'REVIEWS_SORT_SET',
  REVIEWS_SEARCHEDTERM_SET:'REVIEWS_SEARCHEDTERM_SET',
  REVIEWS_SEARCHEDTERM_CLEAR:'REVIEWS_SEARCHEDTERM_CLEAR',
}