export default {
  REVIEWS_FETCH:'REVIEWS_FETCH',
  REVIEWS_FETCH_SORTED:'REVIEWS_FETCH_SORTED',
  REVIEWS_FETCH_SEARCH:'REVIEWS_FETCH_SEARCH',
  REVIEWS_SET_LANGUAGE:'REVIEWS_SET_LANGUAGE',
  REVIEWS_UPDATE:'REVIEWS_UPDATE',
}