export default {
  USER_REVIEW_POST:'USER_REVIEW_POST',
  USER_REVIEW_CANCEL: 'USER_REVIEW_CANCEL',
  USER_REVIEW_ERROR:'USER_REVIEW_ERROR',
  USER_REVIEW_ADD:'USER_REVIEW_ADD',
  USER_STARS_SELECT:'USER_STARS_SELECT',
  USER_STARS_CLEAR: 'USER_STARS_CLEAR',
  USER_REVIEW_START: 'USER_REVIEW_START'
};